# Generated by Django 5.1.4 on 2025-02-18 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='providerservicerequest',
            old_name='created_at',
            new_name='submitted_at',
        ),
        migrations.AlterField(
            model_name='providerservicerequest',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
