# Generated by Django 5.1.4 on 2025-02-19 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='review'),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='review'),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='products',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='spareparts.product'),
            preserve_default=False,
        ),
    ]
