# Generated by Django 5.1.4 on 2025-02-19 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts', '0003_product_image_productdetails_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='storecategory',
        ),
    ]
