# Generated by Django 5.1.4 on 2025-02-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts', '0004_remove_product_storecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('net_banking', 'Net Banking'), ('cod', 'Cash on Delivery')], default='cod', max_length=20),
        ),
    ]
